version: '3.7'

services:
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mysql
    depends_on:
      - mysql
    environment: 
      DATABASE_URL: "mysql://root:password@mysql:3306/test"
      NODE_ENV: development  # Ajusta según sea necesario
      PORT: 3000
      SECRET_KEY: "I4MEJ2jCVQWHMnkiJIcOyVo+UIFbMlL0qbDslO2szhE="
      LOG_FORMAT: 'combined'
      LOG_DIR: '/logs'
      ORIGIN: 'http://localhost:3000'
      CREDENTIALS: 'true'
    #command: /bin/bash ./wait-for-it
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - '3306:3306'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
